// Generated by Wrangler on Tue Jul 09 2024 10:39:42 GMT+0800 (Malaysia Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	R2: R2Bucket;
	DB: D1Database;
	AI: Ai;
}
